### ISSUE TITLE
Unable to add routing rule that blocks bittorrent

### ISSUE THREAD

**Issue by nonenty** [alireza0/x-ui#797]
**Describe the bug**
Unable to add routing rule that blocks bittorrent.

**To Reproduce**
1. Go to 'Xray Settings', 'Routing Rules'
2. If the rule that blocks BitTorrent has already been set, delete it first
3. Click on 'Add Rule'
4. Set Protocol to bittorrent and Outbound Tag to blocked
5. Click on 'Sure'
6. No rule is added and browser console logs as below
  ```
  vue.min.js:6 TypeError: r.protocol.join is not a function
      at xray:1967:68
      at Array.forEach (<anonymous>)
      at wn.get (xray:1961:30)
      at fn.get (vue.min.js:6:26768)
      at fn.evaluate (vue.min.js:6:27918)
      at wn.routingRuleData (vue.min.js:6:29822)
      at wn.eval (eval at Ya (vue.min.js:6:91725), <anonymous>:3:15045)
      at e._render (vue.min.js:6:35481)
      at wn.r (vue.min.js:6:68170)
      at fn.get (vue.min.js:6:26768)
  ```
**Expected behavior**
The rule should be successfully added.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 120.0.6099.72

**Comment by alireza0** [comment]
Thank you for your report. I will fix it soon.
Meanwhile you can use Basic configuration to enable blocking bittorrent protocol.

**Comment by alireza0** [comment]
Done.
Please build it manually or wait for the next version.
